name: Deploy Numberz to Github Pages, including win screen jpg and solutions cache files.

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:

      - name: Download solutions
        run: curl -L https://github.com/NumberzGame/NumberzGame.github.io/releases/download/v0.0.0/pictures.zip -o pictures.zip

      - name: Unzip solutions
        run: unzip pictures.zip

      - run: ls -la

      - name: Move solutions to dist
        run: |
          mkdir -p ./dist/
          mv *.jpg ./dist/

      - run: ls -la ./dist/

      # To allow possibly including other content on this home 
      # page in future as well, we pull in Numberz
      # from its sister repo home, into this mostly empty repo.   
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     repository: NumberzGame/Numberz

      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build
      #   run: npm run build
         
      # - name: Setup Pages
      #   uses: actions/configure-pages@v4

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: './dist'

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
